Feature: upgrade keycloak
Onlineberatung/onlineberatung-keycloak-otp pull request #16
Opened 2022-03-16 16:01 UTC by hill-daniel

2022-03-16 16:19 UTC, webatspeed approved these changes

2022-03-17 07:02 UTC, mebo4b requested changes

2022-03-17 07:02 UTC, maeventer commented on src/main/java/de/diakonie/onlineberatung/log/LoggingEventListenerProvider.java
> +  private final EventListenerTransaction tx = new EventListenerTransaction(this::logAdminEvent,
Could we find a better name than "tx" e.g. listenerTransaction?

2022-03-17 07:02 UTC, maeventer commented on src/main/java/de/diakonie/onlineberatung/log/LoggingEventListenerProvider.java
> +    if (event.getDetails() != null) {
Could you please extract the details, session and trace logs in several methods to shorten the lines of this method?

2022-03-17 07:02 UTC, mebo4b commented on src/main/java/de/diakonie/onlineberatung/log/LoggingEventListenerProvider.java
> +    for (Map.Entry<String, Cookie> e : headers.getCookies().entrySet()) {
Could we rename "e" to "cookie" please?

2022-03-17 07:02 UTC, mebo4b commented on src/main/java/de/diakonie/onlineberatung/log/LoggingEventListenerProvider.java
> +    boolean f = true;
Could we also please rename "f" to something like "isFirstEntry"?

2022-03-17 07:43 UTC, mebo4b approved these changes

2022-03-17 07:43 UTC, merged