Feat 2 fa via mail authenticator
Onlineberatung/onlineberatung-keycloak-otp pull request #7
Opened 2022-02-10 17:08 UTC by hill-daniel

2022-02-11 06:14 UTC, webatspeed approved these changes

2022-02-11 06:16 UTC, webatspeed requested changes
There are conflicting files.

2022-02-14 10:00 UTC, webatspeed approved these changes

2022-02-14 10:00 UTC, webatspeed commented on src/main/java/de/diakonie/onlineberatung/otp/OtpMailSender.java
>  import de.diakonie.onlineberatung.otp.Otp;
Not needed anymore, right?

2022-02-14 10:00 UTC, webatspeed commented on README.md
> +* Copy `keycloak-otp-config-spi-<VERSION>-keycloak.jar` into the keycloak deplyoments folder. E.g. `/opt/jboss/keycloak/standalone/deployments`
typo in "deplyom..."

2022-02-14 10:07 UTC, hill-daniel commented on src/main/java/de/diakonie/onlineberatung/otp/OtpMailSender.java
>  import de.diakonie.onlineberatung.otp.Otp;
yes :)

2022-02-16 15:43 UTC, merged